---
# ----------------------------------------
# проектный файл для проекта
# ----------------------------------------
project:
  start: main/usr.json  # файл - с которого можно начать чтение, в нем могут быть ссылки на другие файлы

  name: ReDocRedmine       # уникальное имя проекта 

  files:                # список файлов проекта - массив строк
  - main:               # каждый элемент массива - это подпапка в каталоге проекта на сервере. Например папка /main
    - usr.json          # файл с описанием таблиц
  - scripts:             # подкаталог со скриптами/scripts
    - redmineMethods.js  # файл с функционалом Redmine